### ISSUE TITLE
how to open .java

### ISSUE THREAD

**Issue by L33TCHY** [summerfences/iRacing-Cart-Calculator-GUI#2]
Hi,

sorry I'm a bit of a layman in JAVA, how can I open this data so that I can use it?

Thank you very much.

**Comment by summerfences** [comment]
Hello! I'm sorry for the late resopnse, and I'm glad that you got it figured out, but for future reference for anyone who finds this ticket: as long as Java is installed on the system from https://www.java.com/en/ the .jar should work as an executable.

Thanks for your interest in the program!

**Comment by L33TCHY** [comment]
> Hello! I'm sorry for the late resonse, and I'm glad that you got it figured out, but for future reference for anyone who finds this ticket as long as Java is installed on the system from https://www.java.com/en/ the .java should work as an executable.
> 
> Thanks for your interest in the program!

Sorry I had to ask if I didn't look properly beforehand. I didn't see the executable .jar file in the Release section.

Sorry again =/
